/* Optional One Bee resource: source boundaries, duplicate handling and practice selection. */
const assert = require('assert'), fs = require('fs'), path = require('path');
globalThis.window = globalThis;
for (const file of ['data/beewords', 'data/onebeewords', 'bee']) eval(fs.readFileSync(path.join(__dirname, '..', 'js', file + '.js'), 'utf8'));
const extra = BEE_EXTRA_LISTS[0], words = extra.words.map(x => x[0]);
assert.strictEqual(words.length, 947);
assert.strictEqual(new Set(words).size, words.length);
assert(words.every(w => /^[a-zñ]+(?:[ -][a-z]+)*$/.test(w)), 'no PDF headings or footers');
for (const w of ['acrobat', 'zooming', 'punting', 'parsley', 'pattern', 'thistle', 'señor', 'grown-ups', 'fuddy-duddy', 'gung ho', 'dim sum', 'favourite', 'formalise', 'imposter', 'squawl', 'marvellous']) assert(words.includes(w), w);
for (const w of ['abdicate', 'gallop', 'hexagonal', 'lacrosse', 'difficulty', 'hosted', 'or']) assert(!words.includes(w), 'outside One Bee: ' + w);
const all = Bee.flatten(BEE_GROUPS, []), original = BEE_GROUPS.flatMap(g => g.words.map(x => x[0]));
assert.strictEqual(new Set(all.map(x => x.w)).size, all.length);
assert.strictEqual(all.length, new Set(original.concat(words)).size);
const state = Bee.blank(), pool = Bee.pool(state, all);
assert.strictEqual(pool.length, all.length, 'all built-in words are enabled by default');
assert(words.every(w => pool.some(x => x.w === w)));
assert(pool.every(x => [1, 2, 3].includes(x.tier) && x.lists.includes('grade1')));
assert.deepStrictEqual(Bee.norm({ active: ['onebee-extra'] }).active, ['grade1']);
assert.deepStrictEqual(Bee.norm({ active: ['grade1', 'onebee-extra', 'school'] }).active, ['grade1', 'school']);
const sharedGroup = BEE_GROUPS.find(g => g.words.some(x => words.includes(x[0])));
const shared = sharedGroup.words.find(x => words.includes(x[0]));
assert.strictEqual(pool.find(x => x.w === shared[0]).def, shared[1]);
state.tiers = [1];
assert(Bee.pool(state, all).every(x => x.tier === 1));
state.tiers = [1, 2, 3];
const session = Bee.buildSession(state, pool, '2026-09-30');
assert(session.order.length > 0 && session.order.every(x => pool.includes(x)));
console.log('Combined Bee resource tests OK (' + pool.length + ' words)');
// every word, built in or imported, has a meaning and a sentence that contains the word
const missingText = all.filter(x => !x.def || !x.sent || !new RegExp(x.w.replace(/[-.]/g, '\\$&'), 'i').test(x.sent));
assert.deepStrictEqual(missingText.map(x => x.w), [], 'every word needs a meaning and a sentence using it');
console.log('All words have meanings and sentences');
