/* Optional browser regression checks. Requires Playwright.
   Run: node tests/ux.browser.check.js
   BROWSER_EXECUTABLE can select an installed Chromium browser. Test data is isolated. */
const {chromium}=require('playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
(async()=>{const server=http.createServer((q,r)=>{const f=path.join(path.join(__dirname, '..'),q.url.split('?')[0]==='/'?'index.html':q.url.split('?')[0]);try{r.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');r.end(fs.readFileSync(f));}catch{r.statusCode=404;r.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let b;try{b=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {})});const origin='http://127.0.0.1:'+server.address().port;
for(const width of [390,768])for(const colorScheme of ['light','dark']){const ctx=await b.newContext({viewport:{width,height:900},colorScheme,serviceWorkers:'block'});await ctx.addInitScript(() => localStorage.setItem('grade1math.v1', JSON.stringify({ done: { '8': { correct: 3, total: 4, at: 100 } }, right: { '8': { '0': true } }, bee: { xp: 200, words: { cat: { box: 4, ok: 4 } } } })));const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(origin+'/#/');await p.locator('main h1').waitFor();assert(await p.locator('.home-guide .kn-wrap').isVisible());assert(await p.locator('.home-guide .kn-wrap').evaluate(e=>e.getBoundingClientRect().top<300));assert(await p.locator('.go').first().evaluate(e=>e.getBoundingClientRect().top<650),'Home action buried');assert.strictEqual(await p.getByRole('button',{name:/already know/}).count(),0);await p.screenshot({path:`/tmp/ux-home-${width}-${colorScheme}.png`});
await p.goto(origin+'/#/map/math');await p.locator('main h1').waitFor();assert.strictEqual(await p.locator('.map-level[open]').count(),1);assert.strictEqual(await p.getByRole('button',{name:/already know|Choose lessons to change/}).count(),0);await p.screenshot({path:`/tmp/ux-map-${width}-${colorScheme}.png`});
await p.goto(origin+'/#/lesson/0');await p.getByRole('button',{name:/Practice/}).click();assert(await p.locator('.arena-compact').count());await p.screenshot({path:`/tmp/ux-lesson-${width}-${colorScheme}.png`});
await p.goto(origin+'/#/bee');await p.locator('.drillbtn').waitFor();assert(await p.locator('.drillbtn').evaluate(e=>e.getBoundingClientRect().top<350));assert(await p.locator('.bee-hero').evaluate(e=>!e.checkVisibility()));await p.screenshot({path:`/tmp/ux-bee-${width}-${colorScheme}.png`});
await p.goto(origin+'/#/bee/drill');await p.locator('.studycard .bee-letters').waitFor();assert.strictEqual(await p.locator('.studycard .pr-line').count(),2);await p.getByRole('button',{name:'I am ready, try it ➜'}).click();assert.strictEqual(await p.locator('.studycard .bee-letters').count(),0);
await p.goto(origin+'/#/bee/words');await p.getByRole('searchbox',{name:'Search words'}).fill('señor');assert(await p.locator('.bee-browser .wordgrid').innerText().then(t=>t.includes('señor')));await p.getByRole('searchbox').fill('');await p.getByRole('button',{name:'More words',exact:true}).click();assert(await p.getByRole('status').innerText().then(t=>t.includes('41–80')));await p.getByRole('combobox',{name:'Word difficulty'}).selectOption('3');assert(await p.getByRole('status').innerText().then(t=>t.includes('Words 1–40')));await p.screenshot({path:`/tmp/ux-words-${width}-${colorScheme}.png`});
await p.goto(origin+'/#/parent');await p.getByRole('dialog').waitFor();assert(await p.getByRole('button',{name:'Back to the quest'}).evaluate(e=>e===document.activeElement));await p.getByRole('button',{name:'Back to the quest'}).click();assert.strictEqual(await p.getByRole('dialog').count(),0);
await p.evaluate(()=>sessionStorage.setItem('grownupsUntil',String(Date.now()+600000)));await p.goto(origin+'/#/parent');await p.locator('.parent-section').first().waitFor();assert.strictEqual(await p.locator('.parent-section').count(),5);await p.locator('#parent-progress>summary').click();assert.strictEqual(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);await p.screenshot({path:`/tmp/ux-parent-${width}-${colorScheme}.png`});await p.locator('#parent-progress details>summary').first().click();assert.strictEqual(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);
await p.locator('#parent-data>summary').click();assert(await p.getByRole('button',{name:'Reset everything',exact:true}).isVisible());
const saved=await p.evaluate(()=>window.AppKit.S);assert.strictEqual(saved.done['8'].correct,3);assert.strictEqual(saved.right['8']['0'],true);assert.strictEqual(saved.bee.xp,200);assert.strictEqual(saved.bee.words.cat.box,4);
await p.evaluate(()=>{const B=window.AppKit.S.bee;B.active=['test'];B.lists=[{id:'test',name:'Test',words:[['cat','','',1]]}];B.words={cat:{box:1,ok:1,due:'2000-01-01'}};B.mode='say';B.sound=false;});await p.goto(origin+'/#/bee/drill');await p.getByRole('button',{name:'👀 Show me the letters',exact:true}).click();await p.getByRole('button',{name:'✅ I spelled it right',exact:true}).click();await p.getByRole('button',{name:'Finish ➜',exact:true}).click();assert(await p.getByRole('button',{name:'Try 5 more words',exact:true}).isVisible());assert(await p.locator('.bee-rewards').evaluate(e=>!e.open));await p.screenshot({path:`/tmp/ux-done-${width}-${colorScheme}.png`});await p.getByRole('button',{name:'Try 5 more words',exact:true}).click();assert(await p.locator('.wordcard').isVisible());
await p.evaluate(()=>{window.AppKit.S.bee.words={};});await p.goto(origin+'/#/bee');await p.goto(origin+'/#/bee/drill');await p.getByRole('button',{name:'I am ready, try it ➜'}).click();assert.strictEqual(await p.locator('.bee-tiles-input,input[type=text]').count(),0);await p.getByRole('button',{name:'👀 Show me the letters',exact:true}).click();await p.getByRole('button',{name:'✅ I spelled it right',exact:true}).click();await p.getByRole('button',{name:'Start spelling ✏️',exact:true}).click();await p.getByRole('button',{name:'👀 Show me the letters',exact:true}).click();await p.getByRole('button',{name:'❌ Not yet',exact:true}).click();assert.strictEqual(await p.locator('.wordcard input').count(),0);await p.getByRole('button',{name:'👀 Show me the letters',exact:true}).click();await p.getByRole('button',{name:'❌ Not yet',exact:true}).click();await p.getByRole('button',{name:'👀 Show me the letters',exact:true}).click();await p.getByRole('button',{name:'✅ I spelled it right',exact:true}).click();await p.getByRole('button',{name:'Next word ➜',exact:true}).click();assert(await p.getByRole('button',{name:'👀 Show me the letters',exact:true}).isVisible());
assert.deepStrictEqual(errors,[]);console.log(width,colorScheme,'UX checks OK');await ctx.close();}
}finally{if(b)await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
